version: "3"

services:
  mongo:
    container_name: mongo
    image: mongo:5
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  firebase-emulators:
    container_name: firebase-emulators
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
    build:
      context: .
      dockerfile: Dockerfile.firebase
    image: firebase-emulator:firebase-emulator
    volumes:
      - ./firebase.json:/src/firebase.json
      - ./storage.rules:/src/storage.rules
      - ./firebase-seed-data:/src/firebase-seed-data
    command: firebase emulators:start --project dev --export-on-exit=./firebase-seed-data --import=./firebase-seed-data --debug

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - firebase-emulators
    ports:
      - 5000:5000
      - 5555:5555
    volumes:
      - ./api:/usr/app
    env_file:
      - .env
    command: npm run local

  web:
    depends_on:
      - mongo
      - firebase-emulators
    ports:
      - 3000:3000
    build:
      context: ./web
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    environment:
      - DB_CONNECTION_STRING=mongodb://root:example@mongo:27017/myFirstDatabase
      - ENVIRONMENT=DEVELOPMENT
      - NEXT_PUBLIC_ENVIRONMENT=DEVELOPMENT
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulators:4001
      - FIREBASE_STORAGE_EMULATOR_HOST=firebase-emulators:4002
      - NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST=localhost:4001
      - NEXT_PUBLIC_FIREBASE_STORAGE_EMULATOR_HOST=localhost:4002
    volumes:
      - ./web:/app
      - /web/app/node_modules
      - /web/app/.next

volumes:
  mongodata:
