version: "3"

services:
  cypress:
    container_name: cypress
    image: cypress
    build:
      context: ./cypress
      dockerfile: Dockerfile
    depends_on:
      - web
    env_file:
      - .env
    environment:
      - CYPRESS_baseUrl=http://web:3000
    command: npx cypress run
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.json:/app/cypress.json

  # Couldn't get connection strings to work correctly locally.
  # Will continue to use the dev database on Atlas for now...
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - /data/db:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  firebase-emulators:
    container_name: firebase-emulators
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
    build:
      context: .
      dockerfile: Dockerfile.firebase
    image: firebase-emulator:firebase-emulator
    volumes:
      - .:/src
    command: firebase emulators:start --project dev

  api:
    container_name: api
    image: ghcr.io/kittrgg/monorepo/api:test
    depends_on:
      # - mongo
      - firebase-emulators
    ports:
      - 5000:5000
      - 5555:5555
    command: npm run local

  web:
    container_name: web
    depends_on:
      # - mongo
      - firebase-emulators
    ports:
      - 3000:3000
    image: ghcr.io/kittrgg/monorepo/web:test
