version: "3"

services:
  cypress:
    container_name: cypress
    image: cypress
    build:
      context: ./cypress
      dockerfile: Dockerfile
    depends_on:
      - web
    environment:
      - CYPRESS_baseUrl=http://web:3000
      - DB_CONNECTION_STRING=${CI_DB_CONNECTION_STRING}
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulators:4001
      - FIREBASE_STORAGE_EMULATOR_HOST=firebase-emulators:4002
    command: npx cypress run
    volumes:
      - ./cypress:/app/cypress
      - ./cypress.json:/app/cypress.json

  # Couldn't get connection strings to work correctly locally.
  # Will continue to use the dev database on Atlas for now...
  # mongo:
  #   container_name: mongo
  #   image: mongo
  #   restart: always
  #   ports:
  #     - 27017:27017
  #   volumes:
  #     - /data/db:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  firebase-emulators:
    container_name: firebase-emulators
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
    build:
      context: .
      dockerfile: Dockerfile.firebase
    image: firebase-emulator:firebase-emulator
    volumes:
      - .:/src
    command: firebase emulators:start --project dev

  api:
    container_name: api
    build:
      context: ./api
      dockerfile: Dockerfile
    depends_on:
      # - mongo
      - firebase-emulators
    ports:
      - 5000:5000
      - 5555:5555
    volumes:
      - ./api:/usr/app
    environment:
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulators:4001
      - FIREBASE_STORAGE_EMULATOR_HOST=firebase-emulators:4002
    command: npm run local

  web:
    container_name: web
    depends_on:
      # - mongo
      - firebase-emulators
    ports:
      - 3000:3000
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - ENVIRONMENT=TESTING
        - NEXT_PUBLIC_ENVIRONMENT=TESTING
        - DB_CONNECTION_STRING=${CI_DB_CONNECTION_STRING}
        - TWITCH_CLIENT_ID=${CI_TWITCH_CLIENT_ID}
        - TWITCH_SECRET=${CI_TWITCH_SECRET}
        - NEXT_PUBLIC_SOCKET_HOST=${CI_NEXT_PUBLIC_SOCKET_HOST}
    environment:
      - ENVIRONMENT=TESTING
      - NEXT_PUBLIC_ENVIRONMENT=TESTING
      - FIREBASE_AUTH_EMULATOR_HOST=firebase-emulators:4001
      - FIREBASE_STORAGE_EMULATOR_HOST=firebase-emulators:4002
      - NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST=localhost:4001
      - NEXT_PUBLIC_FIREBASE_STORAGE_EMULATOR_HOST=localhost:4002
    volumes:
      - ./web:/app
      - /web/app/node_modules
