name: Run E2E

on:
  push:
    branches:
      - e2e

jobs:
  e2e:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: "14"

      - name: Cypress run
        uses: cypress-io/github-action@v2
