name: E2E Testing & Deploy Stage

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cypress Tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run start
          wait-on: "http://localhost:3000"
          wait-on-timeout: 300
          browser: chrome
          spec: cypress/integration/*
        env:
          - CYPRESS_ENVIRONMENT=TESTING
          - CYPRESS_NEXT_PUBLIC_ENVIRONMENT=TESTING
          - CYPRESS_TWITCH_CLIENT_ID=${{secrets.CI_TWITCH_CLIENT_ID}}
          - CYPRESS_TWITCH_SECRET=${{secrets.CI_TWITCH_SECRET}}
          - CYPRESS_TWITCH_CLIENT_SECRET={{secrets.CI_TWITCH_SECRET}}
          - CYPRESS_DB_CONNECTION_STRING=${{secrets.CI_DB_CONNECTION_STRING}}
          - CYPRESS_FIREBASE_AUTH_EMULATOR_HOST=firebase-emulators:4001
          - CYPRESS_FIREBASE_STORAGE_EMULATOR_HOST=firebase-emulators:4002
          - CYPRESS_NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST=localhost:4001
          - CYPRESS_NEXT_PUBLIC_FIREBASE_STORAGE_EMULATOR_HOST=localhost:4002
          - CYPRESS_NEXT_PUBLIC_SOCKET_HOST=${{secrets.CI_NEXT_PUBLIC_SOCKET_HOST}}
