# One day, this will work...
# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: E2E Testing & Deploy Stage

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        name: Use Node.js ${{ matrix.node-version }}
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm install

      - uses: satak/webrequest-action@master
        with:
          url: ${{secrets.NEXT_PUBLIC_SOCKET_HOST}}
          method: GET

      - run: npm run ci
        env:
          DB_CONNECTION_STRING: ${{secrets.CI_DB_CONNECTION_STRING}}
          ENVIRONMENT: ${{secrets.CI_ENVIRONMENT}}
          FIREBASE_AUTH_EMULATOR_HOST: ${{secrets.CI_FIREBASE_AUTH_EMULATOR_HOST}}
          NEXT_PUBLIC_API_KEY: ${{secrets.CI_NEXT_PUBLIC_API_KEY}}
          NEXT_PUBLIC_ENVIRONMENT: ${{secrets.CI_NEXT_PUBLIC_ENVIRONMENT}}
          NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST: ${{secrets.CI_NEXT_PUBLIC_FIREBASE_AUTH_EMULATOR_HOST}}
          NEXT_PUBLIC_FIREBASE_DATABASE_URL: ${{secrets.CI_NEXT_PUBLIC_FIREBASE_DATABASE_URL}}
          FIREBASE_PROJECT_ID: ${{secrets.CI_FIREBASE_PROJECT_ID}}
          FIREBASE_AUTH_DOMAIN: ${{secrets.CI_FIREBASE_AUTH_DOMAIN}}
          FIREBASE_CLIENT_EMAIL: ${{secrets.CI_FIREBASE_CLIENT_EMAIL}}
          FIREBASE_MESSAGING_SENDER_ID: ${{secrets.CI_FIREBASE_MESSAGING_SENDER_ID}}
          FIREBASE_MEASUREMENT_ID: ${{secrets.CI_FIREBASE_MEASUREMENT_ID}}
          FIREBASE_COOKIE_SECRET_PREVIOUS: ${{secrets.CI_FIREBASE_COOKIE_SECRET_PREVIOUS}}
          FIREBASE_COOKIE_SECRET_CURRENT: ${{secrets.CI_FIREBASE_COOKIE_SECRET_CURRENT}}
          NEXT_PUBLIC_SOCKET_HOST: ${{secrets.CI_NEXT_PUBLIC_SOCKET_HOST}}
          NEXT_PUBLIC_GOOGLE_ANALYTICS: ${{secrets.CI_NEXT_PUBLIC_GOOGLE_ANALYTICS}}
          NEXT_PUBLIC_ROLLBAR_ACCESS_TOKEN: ${{secrets.CI_NEXT_PUBLIC_ROLLBAR_ACCESS_TOKEN}}
          NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{secrets.CI_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY}}
          FIREBASE_APP_ID: ${{secrets.CI_FIREBASE_APP_ID}}
          TWITCH_CLIENT_ID: ${{secrets.CI_TWITCH_CLIENT_ID}}
          TWITCH_SECRET: ${{secrets.CI_TWITCH_SECRET}}
          STRIPE_SECRET_KEY: ${{secrets.CI_STRIPE_SECRET_KEY}}
          STRIPE_WEBHOOK_SECRET: ${{secrets.CI_STRIPE_WEBHOOK_SECRET}}
          SUBSCRIPTION_PRICE_ID: ${{secrets.CI_SUBSCRIPTION_PRICE_ID}}
          MONTHLY_TIP_PRICE_ID: ${{secrets.CI_MONTHLY_TIP_PRICE_ID}}
